codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: master  # only use the latest copy on master branch

coverage:
  precision: 2
  round: down
  range: "95...100"

  status:
    project:
      default:
        target: 95
    patch: yes
    changes: no

