version: '2'

services:
    crossdock:
        image: crossdock/crossdock
        links:
            - test_driver
            - go
            - node
            - java
            - python
            - zipkin-brave-json
            - zipkin-brave-thrift

        environment:
            - WAIT_FOR=test_driver,go,node,java,python,zipkin-brave-thrift,zipkin-brave-json
            - WAIT_FOR_TIMEOUT=60s

            - CALL_TIMEOUT=60s

            - AXIS_CLIENT=test_driver
            - AXIS_SERVICES=go,node,java,python,zipkin-brave-json,zipkin-brave-thrift

            - BEHAVIOR_ENDTOEND=client,services

    go:
        image: jaegertracing/xdock-go
        ports:
            - "8080-8082"
        links:
          - "jaeger-agent:test_driver"

    node:
        image: jaegertracing/xdock-node
        ports:
            - "8080-8082"
        links:
          - "jaeger-agent:test_driver"

    java:
        image: jaegertracing/xdock-java
        ports:
            - "8080-8082"
        links:
          - "jaeger-agent:test_driver"

    python:
        image: jaegertracing/xdock-py
        ports:
            - "8080-8082"
        links:
          - "jaeger-agent:test_driver"

    zipkin-brave-json:
        image: jaegertracing/xdock-zipkin-brave
        ports:
            - "8080-8081"
        environment:
            - ENCODING=JSON
        links:
          - "jaeger-collector:test_driver"

    zipkin-brave-thrift:
        image: jaegertracing/xdock-zipkin-brave
        ports:
            - "8080-8081"
        environment:
            - ENCODING=THRIFT
        links:
          - "jaeger-collector:test_driver"

    test_driver:
        image: jaegertracing/test-driver
        ports:
            - "8080"
        links:
          - jaeger-query
          - jaeger-collector
          - jaeger-agent

    jaeger-query:
#    override to disable static files
      command: ["/go/bin/query-linux", "--query.static-files=", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]

